version: "3.7"
services:
  ################################################################
  # The Etcd Cluster
  ################################################################
  # use "curl -L http://localhost:12379/health" to check node health
  etcd_cluster_n1:
    image: quay.io/coreos/etcd:v3.4.10
    hostname: etcd_cluster_n1
    ports:
      - 12379:2379
      - 12380:2380
    environment:
      ETCD_NAME: node1
      ETCD_DATA_DIR: /etcd-data/etcd_cluster_n1.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_cluster_n1:2380
      ETCD_INITIAL_CLUSTER: node1=http://etcd_cluster_n1:2380,node2=http://etcd_cluster_n2:2380,node3=http://etcd_cluster_n3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_cluster_n1:2379
    volumes:
      - ~/etcd/certs00:/srv
      - ~/etcd/data00:/etcd-data
  etcd_cluster_n2:
    image: quay.io/coreos/etcd:v3.4.10
    hostname: etcd_cluster_n2
    ports:
      - 12381:2379
      - 12382:2380
    environment:
      ETCD_NAME: node2
      ETCD_DATA_DIR: /etcd-data/etcd_cluster_n2.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_cluster_n2:2380
      ETCD_INITIAL_CLUSTER: node1=http://etcd_cluster_n1:2380,node2=http://etcd_cluster_n2:2380,node3=http://etcd_cluster_n3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_cluster_n2:2379
    volumes:
      - ~/etcd/certs01:/srv
      - ~/etcd/data01:/etcd-data
  etcd_cluster_n3:
    image: quay.io/coreos/etcd:v3.4.10
    hostname: etcd_cluster_n3
    ports:
      - 12383:2379
      - 12384:2380
    environment:
      ETCD_NAME: node3
      ETCD_DATA_DIR: /etcd-data/etcd_cluster_n3.etcd
      ETCDCTL_API: 3
      ETCD_DEBUG: 1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_cluster_n3:2380
      ETCD_INITIAL_CLUSTER: node1=http://etcd_cluster_n1:2380,node2=http://etcd_cluster_n2:2380,node3=http://etcd_cluster_n3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_cluster_n3:2379
    volumes:
      - ~/etcd/certs02:/srv
      - ~/etcd/data02:/etcd-data
