version: '3.7'
services:
  seaweedfs_master:
    image: chrislusf/seaweedfs:1.44
    ports:
      - 9333:9333
      - 19333:19333
      - 8080:8080
      - 18080:18080
      - 8888:8888
      - 18888:18888
    command: '-v=2 server -master.dir=/data -dir=/data -master.volumeSizeLimitMB=1000 -volume.max=1000'
    volumes:
      - ~/seaweedfs:/data
  
  seaweedfs_volume:
    image: chrislusf/seaweedfs:1.44
    ports:
    - 8080:8080
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -port=8080'
    depends_on:
    - seaweedfs_master

  seaweedfs_filer:
    image: chrislusf/seaweedfs:1.44
    ports:
    - 8888:8888
    - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
    - seaweedfs_master
    - seaweedfs_volume

  seaweedfs_cronjob:
    image: chrislusf/seaweedfs:1.44
    command: 'cronjob'
    environment:
      # run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: seaweedfs_master:9333 # Default: localhost:9333
    depends_on:
    - seaweedfs_master
    - seaweedfs_volume
    
  seaweedfs_s3:
    image: chrislusf/seaweedfs:1.44
    ports:
    - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
    - seaweedfs_master
    - seaweedfs_volume
    - seaweedfs_filer
