version: "3.7"
networks:
  cassandra_net:
    external:
      name: component-net
services:
  cassandra-001:
    image: cassandra:3.11.5
    container_name: cassandra_001
    hostname: cassandra-001
    ports:
      - "9042:9042" # CQL native transport port
    environment:
      MAX_HEAP_SIZE: "256M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-001"
    volumes:
      - /data/cassandra/data_01:/var/lib/cassandra
    networks:
      - cassandra_net
