version: "3.7"
# networks:
#   cassandra_net:
#     external:
#       name: component-net
services:
  ################################################################
  # The Cassandra Cluster
  ################################################################
  # use "env CQLSH_HOST=cassandra_cluster_n1 && cqlsh" to connect to server
  cassandra_cluster_n1:
    image: cassandra:3.11.5
    container_name: cassandra_cluster_n1
    hostname: cassandra_cluster_n1
    ports:
      - "17000:7000" # Internode communication (not used if TLS enabled)
      - "19042:9042" # CQL native transport port
    environment:
      MAX_HEAP_SIZE: "256M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra_cluster_n1"
    volumes:
      - /data/cassandra00:/var/lib/cassandra
    # networks:
    #   - cassandra_net

  cassandra_cluster_n2:
    image: cassandra:3.11.5
    container_name: cassandra_cluster_n2
    hostname: cassandra_cluster_n2
    depends_on:
      - cassandra_cluster_n1
    ports:
      - "17001:7000" # Internode communication (not used if TLS enabled)
      - "19043:9042" # CQL native transport port
    environment:
      MAX_HEAP_SIZE: "256M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra_cluster_n2"
      CASSANDRA_SEEDS: "cassandra_cluster_n1"  
    volumes:
      - /data/cassandra01:/var/lib/cassandra
    # networks:
    #   - cassandra_net
    
  cassandra_cluster_n3:
    image: cassandra:3.11.5
    container_name: cassandra_cluster_n3
    hostname: cassandra_cluster_n3
    depends_on:
      - cassandra_cluster_n1
    ports:
      - "17002:7000" # Internode communication (not used if TLS enabled)
      - "19044:9042" # CQL native transport port
    environment:
      MAX_HEAP_SIZE: "256M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra_cluster_n3"
      CASSANDRA_SEEDS: "cassandra_cluster_n1"
    volumes:
      - /data/cassandra02:/var/lib/cassandra
    # networks:
    #   - cassandra_net
