version: '3.7'
services:
  zk:
    image: zookeeper:3.5
    hostname: zk
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "a.b.c.d" # localhost ip
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_CREATE_TOPICS: "face-engine-data:1:1,face-feature-data:1:1,face-garbage-data:1:1,engine-object-info:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 200000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
