version: '3.7'
services:
  ################################################################
  # The Zookeeper cluster 
  #   - zookeeper-node1
  ################################################################  
  zk1:
    image: zookeeper:3.5
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  ################################################################
  # The Zookeeper cluster 
  #   - zookeeper-node2
  ################################################################        
  zk2:
    image: zookeeper:3.5
    hostname: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
  ################################################################
  # The Zookeeper cluster 
  #   - zookeeper-node3
  ################################################################        
  zk3:
    image: zookeeper:3.5
    hostname: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  
  ################################################################
  # The Kafka cluster 
  #   - kafka-node1
  ################################################################       
  kafka1:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "a.b.c.d" # localhost ip
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
      KAFKA_CREATE_TOPICS: "face-engine-data:3:3,face-feature-data:3:3,face-garbage-data:3:3,engine-object-info:3:3"
      KAFKA_MESSAGE_MAX_BYTES: 200000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ################################################################
  # The Kafka cluster 
  #   - kafka-node2
  ################################################################        
  kafka2:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "a.b.c.d" # localhost ip
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
      KAFKA_CREATE_TOPICS: "face-engine-data:3:3,face-feature-data:3:3,face-garbage-data:3:3,engine-object-info:3:3"
      KAFKA_MESSAGE_MAX_BYTES: 200000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ################################################################
  # The Kafka cluster 
  #   - kafka-node3
  ################################################################        
  kafka3:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "a.b.c.d" # localhost ip
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
      KAFKA_CREATE_TOPICS: "face-engine-data:3:3,face-feature-data:3:3,face-garbage-data:3:3,engine-object-info:3:3"
      KAFKA_MESSAGE_MAX_BYTES: 200000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
